### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'repos'

### ISSUE THREAD

**Issue by demonicpagan** [aaugustin/trac-github#62]
I am running Trac version 1.0.2 and I installed this plugin per the instructions in the REAMDME with the exclusion of putting repository information in the [trac] area, I have it in the [repositories] area.

With that being said, here are those 2 sections:

[repositories]
stormbot7.alias = sb7
stormbot7.description = Stormbot v7 Git repository
stormbot7.dir = /home/bhnet/bhtrac/Stormbot7.git
stormbot7.type = git
stormbot7.url = https://github.com/StormbotTCL/Stormbot7

[trac]
auto_preview_timeout = 2.0
auto_reload = false
base_url = trac.stormbot.org
database = **database information**
debug_sql = false
default_date_format = iso8601
default_language = en_US
default_timezone = America/New_York
genshi_cache_size = 128
mainnav = wiki, blog, timeline, browser, tickets, newticket, search
repository_type = git
secure_cookies = false
use_base_url_for_redirect = false

Here are my [git] and [github] settings of my configuration as well.

[git]
git_bin = /usr/bin/git
post_request_ips = 204.232.175.64/27List of IPs (in CIDR format) POST request is accepted from.192.30.252.0/22
shortrev_len = 7
wiki_shortrev_len = 40
wikishortrev_len = 40

[github]
repository = StormbotTCL/Stormbot7

http://trac.stormbot.org/github does show the endpoint

Setup of the webhook is pointing to that address with the content type of application/json. The initial test passed but any updates to the repo come back with a 500 error with "AttributeError: 'NoneType' object has no attribute 'repos' reported in the GitHub log for the webhook.

If there is any more information I need to provide, I will do so.

**Comment by aaugustin** [comment]
The stack trace for the crash should be in Trac's log. Could you find it and paste it?

**Comment by demonicpagan** [comment]
Here it is, I think I captured everything.

2015-02-28 00:39:48,259 Trac[main] DEBUG: Dispatching <RequestWithSession "POST '/github'">
2015-02-28 00:39:48,265 Trac[main] DEBUG: Negotiated locale: None -> en_US
2015-02-28 00:39:48,326 Trac[api] WARNING: Unable to find repository '(default)' for synchronization
2015-02-28 00:39:48,328 Trac[main] ERROR: Internal Server Error: 
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/trac/web/main.py", line 512, in _dispatch_request
    dispatcher.dispatch(req)
  File "build/bdist.linux-x86_64/egg/trac/web/main.py", line 221, in dispatch
    resp = chosen_handler.process_request(req)
  File "build/bdist.linux-x86_64/egg/tracext/github.py", line 204, in process_request
    git = repos.repos.git.repo       # GitCachedRepository
AttributeError: 'NoneType' object has no attribute 'repos'
2015-02-28 00:39:48,329 Trac[perm] DEBUG: No policy allowed anonymous performing TRAC_ADMIN on None
2015-02-28 00:39:48,330 Trac[chrome] DEBUG: Prepare chrome data for request
2015-02-28 00:39:48,331 Trac[perm] DEBUG: No policy allowed anonymous performing TICKET_CREATE on None
2015-02-28 00:39:48,402 Trac[git_fs] INFO: detected GIT version 2.1.4
2015-02-28 00:39:48,404 Trac[PyGIT] DEBUG: PyGIT.Storage instance 140697360435920 constructed
2015-02-28 00:39:48,404 Trac[PyGIT] DEBUG: requested weak PyGIT.Storage instance 140697360435920 for '/home/bhnet/bhtrac/Stormbot7.git'
2015-02-28 00:39:48,404 Trac[git_fs] DEBUG: disabled CachedRepository for '/home/bhnet/bhtrac/Stormbot7.git'

**Comment by aaugustin** [comment]
In fact, you should point GitHub to http://trac.stormbot.org/github/sb7, since you repo's alias is sb7.

However trac-github could fail more gracefully in that case.

Currently line 193 of `build/bdist.linux-x86_64/egg/tracext/github.py` contains:

    if path != '/':

Could you try changing it to:

    if repos is None or path != '/':

That should give a better error messages when you're hitting http://trac.stormbot.org/github.

**Comment by demonicpagan** [comment]
The problem I am having with that is that it is loaded from a python egg file located at /usr/local/lib/python2.7/dist-packages/trac_github-2.1.1-py2.7.egg

**Comment by aaugustin** [comment]
OK, never mind, I think I can figure out what I need from Trac's source code. Thanks for reporting this bug!

**Comment by demonicpagan** [comment]
Sounds good. I look forward to seeing what you come up with as to what is going on.

**Comment by aaugustin** [comment]
I uploaded to PyPI a new version including this fix.
